name: flutter_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # for routing => https://pub.dev/packages/auto_route
  auto_route: ^7.8.3

  # for functional programming => https://pub.dev/packages/dartz
  dartz: ^0.10.1

  # for network requests => https://pub.dev/packages/dio
  dio: ^5.3.3

  # a dio interceptor for retry requests => https://pub.dev/packages/dio_smart_retry
  dio_smart_retry: ^5.0.0

  # for equality => https://pub.dev/packages/equatable
  equatable: ^2.0.5

  flutter:
    sdk: flutter

  # for state management => https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.3

  # for environments => https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.1.0

  # for responsibility => https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0

  # for dependency injection => https://pub.dev/packages/get_it
  get_it: ^7.6.4

  intl: ^0.18.1

  # for creating api models => https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1

  # a dio interceptor for developer => https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  # auto_route generator => https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^7.3.1

  # for testing bloc => https://pub.dev/packages/bloc_test
  bloc_test: ^9.1.4

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  # for creating api models => https://pub.dev/packages/json_serializable
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
