name: flutter_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavor: ^3.1.3
  flutter_hooks: ^0.20.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  shared_preferences: ^2.2.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  dio_smart_retry: ^5.0.0
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1

flutter:
  uses-material-design: true
